config/routes.rb
Rails.application.routes.draw do

  root 'movies#index'

  resources :movies do
    resources :actors 
  end

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  belongs_to :movies

def full_details(show_all = true)
   "#{self.first_name} - #{self.age}"
 end

 def i
   "#{self.movies.first_name} - #{self.movie.age}"
 end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :actors, dependent: :destroy 

  def actor_show(first_name, last_name, age, born)
    self.actors.each do |actor|
     actor.first_name = first_name
     actor.last_name = last_name
     actor.age = age
     actor.born = born
     actor.save
   end
 end
end

app/controllers/actor_controller.rb
class ActorController < ApplicationController
  def index
    @actors = Actor.all
  end

  def show
    @actor = Actor.find(params[:id])
  end

  def new
    @actor = Actor.new
  end

def create
   @actor = Actor.new(actor_params)
 
   if @actor.save
     redirect_to actors_path
   else
     render :new
   end

   def edit
   @actor = Actor.find(params[:id])
 end

def update
 @actor = Actor.find(params[:id])
 
 if @actor.update(actor_params)
   redirect_to actors_path
 else
   render :edit
 end
end

def destroy
 @actor = Actor.find(params[:id])
 @actor.destroy
 redirect_to actors_path
end

 end


private

 def actor_params
   params.require(:actor).permit(:first_name, :last_name, :age, :born)
 end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
    @actors = Actor.all
  end

  def show
    @actor = Actor.find(params[:id])
  end

  def new
    @actor = Actor.new
    @movie = params[:movie_id]
  end

def create
   @actor = Actor.new(actor_params)
   @actor.movie_id = params[:movie_id]
    
   if @actor.save
     redirect_to movie_path(params[:movie_id])
   else
     render :new
   end

   def edit
   @actor = Actor.find(params[:id])
 end

def update
 @actor = Actor.find(params[:id])
 
 if @actor.update(actor_params)
   redirect_to actors_path
 else
   render :edit
 end
end

def destroy
 @actor = Actor.find(params[:id])
 @actor.destroy
 redirect_to actors_path
end

 end


private

 def actor_params
   params.require(:actor).permit(:first_name, :last_name, :age, :born)
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    @actors = @movie.actors
    return @movie if @movie
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
   if @movie.save
     redirect_to movies_path
   else
     render :new
  end 

  def edit
    @movie = Movie.find(params[:id])
  end  

  def update
    @movie = Movie.find(params[:id])
  
  if @movie.update(movie_params)
    redirect_to movies_path
  else
    render :edit
  end
end

  def destroy
     @movie = Movie.find(params[:id])
     @movie.destroy
     redirect_to movies_path
end
end

private
  def movie_params
   params.require(:movie).permit(:title, :rating, :description, :length)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/actor_helper.rb
module ActorHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/actor/index.html.erb
<h1> Actors </h1>
<p><%= link_to 'Add Actor', new_actor_path %>
<% @actors.each do |actor| %>
 <h2><%= actor.first_name %></h2>
 <h3><%= actor.last_name %></h3>
 <p><%= actor.age %></p>
 <p><%= actor.born %></p>
 <%= link_to 'Show Actor', actor_path(actor) %>
 <%= link_to 'Edit Actor', edit_actor_path(actor) %>
 <%= link_to 'Delete Actor', actor, method: :delete %>
<% end %>

app/views/actor/new.html.erb
<h1> New Actor </h1>
<%= form_for @actor do |f| %>
 <%= f.label :first_name %>: 
 <%= f.text_field :first_name %>

 <%= f.label :last_name %> 
 <%= f.text_field :last_name %>

 <%= f.label :age %>
 <%= f.text_field :age %>

  <%= f.label :born %>
 <%= f.text_field :born %>

 <%= f.submit %>
 <% end %>

app/views/actor/show.html.erb
<h1> Actor </h1>
<h2><%= @actor.first_name %></h2>
<h3><%= @actor.last_name %></h2>
<p><%= @actor.age %></p>
<p><%= @actor.born %></p>
<%= link_to 'Back', actors_path %>

app/views/actors/edit.html.erb
<h1> Edit Actor </h1>
<%= form_for @actor do |f| %>
 <%= f.label :first_name %>: 
 <%= f.text_field :first_name %>

 <%= f.label :last_name %> 
 <%= f.text_field :last_name %>

 <%= f.label :age %>
 <%= f.text_field :age %>

 <%= f.label :born %>
 <%= f.text_field :born %>


 <%= f.submit %>
<% end %>

app/views/actors/index.html.erb
<h1> Actors </h1>
<p><%= link_to 'Add Actor', new_actor_path %>
<% @actors.each do |actor| %>
 <h2><%= actor.first_name %></h2>
 <h3><%= actor.last_name %></h3>
 <p><%= actor.age %></p>
 <p><%= actor.born %></p>
 <%= link_to 'Show Actor', actor_path(actor) %>
 <%= link_to 'Edit Actor', edit_actor_path(actor) %>
 <%= link_to 'Delete Actor', actor, method: :delete %>
 <p><%= link_to 'Back', movies_path %></p>
<% end %>

app/views/actors/new.html.erb
<h1> New Actor </h1>
<%= form_for @actor, url: movie_actors_path(@movie) do |f| %>
 <%= f.label :first_name %>: 
 <%= f.text_field :first_name %>

 <%= f.label :last_name %> 
 <%= f.text_field :last_name %>

 <%= f.label :age %>
 <%= f.text_field :age %>

  <%= f.label :born %>
 <%= f.text_field :born %>

 <%= f.submit %>
 <% end %>

app/views/actors/show.html.erb
<h1> Actor </h1>
<h2><%= @actor.first_name %></h2>
<h3><%= @actor.last_name %></h2>
<p><%= @actor.age %></p>
<p><%= @actor.born %></p>

<%= link_to 'Back', movie_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<%= yield %>

</body>
</html>

app/views/movies/edit.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="/sin_calc.css">
</head>

<h1> Edit Movie </h1>
<%= form_for @movie do |f| %>
  <%= f.label :title %>: 
  <%= f.text_field :title %>

  <%= f.label :rating %> 
  <%= f.text_field :rating %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :length %>
  <%= f.text_field :length %>

  <%= f.submit %>
<% end %>

app/views/movies/index.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="/sin_calc.css">
</head>

<div class= 'movie'>
<h1> Movies </h1>
<p><%= link_to 'Add Movie', new_movie_path %></p>
<% @movies.each do |movie| %>
<h2><%= movie.title %></h2>
 <%= link_to 'Show Movie', movie_path(movie) %>
 <%= link_to 'Edit Movie', edit_movie_path(movie) %>
 <%= link_to 'Delete Movie', movie, method: :delete %>
<% end %>  
</div>

app/views/movies/new.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="/sin_calc.css">
</head>

<h1> New Movie </h1>
<%= form_for @movie do |f| %>
  <%= f.label :title %>: 
  <%= f.text_field :title %>

  <%= f.label :rating %> 
  <%= f.text_field :rating %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :length %>
  <%= f.text_field :length %>

  <%= f.submit %>
<% end %>

app/views/movies/show.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="moviesite.css">
</head>

<h1> <u>Movie</u> </h1>
  <h2><%= @movie.title %></h2>
  <h3><%= @movie.rating %></h3>
  <p><%= @movie.description %></p>
  <p><%= @movie.length %></p>
  <h1> <u>Actors</u> </h1>
  <% @movie.actors.each do |actor| %>
<div class= 'actors'>
<p>First Name: <%= actor.first_name %></p>
<p>Last Name: <%= actor.last_name %></p>
<p>Age: <%= actor.age %></p>
<p>Date of birth: <%= actor.born %></p>
</div> 
<% end %>
    <p><%= link_to 'Add Actors', new_movie_actor_path(@movie) %></p>
    <p><%= link_to 'Back', movies_path %></p>